name: pgrkam
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.4.0
  google_fonts: ^5.0.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  otp_text_field: ^1.1.3
  percent_indicator: ^4.2.2
  url_launcher: ^6.1.8
  flutter_svg: ^2.0.0+1
  dotted_border: ^2.0.0+3
  flutter_dash: ^1.0.0
  dotted_line: ^3.1.0
  dio: ^5.0.2
  retrofit: ^4.0.1
  json_serializable: ^6.6.1
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  shared_preferences: ^2.1.0
  share_plus: ^7.0.2
  fluttertoast: ^8.2.1
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.3.2
  freezed: ^2.3.0
  retrofit_generator: ^7.0.1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
